---
repos:
    # General

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace

    - repo: https://github.com/sirosen/texthooks
      rev: 0.4.0
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.4
      hooks:
          - id: prettier
            stages: [commit]

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.3.1
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/kraymer/cesar
      rev: v1.0.0
      hooks:
          - id: cesar

    - repo: https://github.com/streetsidesoftware/cspell-cli
      rev: v6.31.0
      hooks:
          - id: cspell

    # Git

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.17.0
      hooks:
          - id: gitlint

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.15.0
      hooks:
          - id: gitleaks

    - repo: https://github.com/rhysd/actionlint
      rev: v1.6.22
      hooks:
          - id: actionlint

    # JSON

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.19.1
      hooks:
          - id: check-github-actions
          - id: check-github-workflows

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-json

    # Markdown

    - repo: https://github.com/tcort/markdown-link-check
      rev: v3.11.2
      hooks:
          - id: markdown-link-check
            args:
                - --config
                - .markdown-link-check.json

    # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.28.0
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    - repo: https://github.com/proinsias/yaml-update-last-modified-date
      rev: v1.1.1
      hooks:
          - id: yaml-update-last-modified-date
# FIXME:
#    * commitizen?
#    * megalinter? - v8r
#    * textlintrc?
#    * https://github.com/igorshubovych/markdownlint-cli ?
#    * https://github.com/DavidAnson/markdownlint-cli2 ?
#    * https://github.com/markdownlint/markdownlint ?
